name: lua_dardo
description: A Lua virtual machine written in Dart, which implements Lua5.3 version.
version: 0.0.3
homepage: https://github.com/arcticfox1919/LuaDardo.git

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  sprintf:
    git:
      url: https://github.com/Eee721/dart-sprintf
      path: .
      ref : ff9df3a79a5f439439666af29b11d37d9d7ef1ed

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
